DR_MINAKSHI_MISHRA = "Dr. Minakshi Mishra"
DR_ABHILASHA_MISHRA = "Dr. Abhilasha Mishra"
DR_AMIT_TRIPATHI = "Dr. Amit Tripathi"
DR_SUVARNA_KUMAR = "Dr. Suvarna Kumar"
DR_RASHMI_SHARMA = "Dr. Rashmi Sharma"
DR_SHARMILA = "Dr. Sharmila"
DR_SAUMYA_SHUKLA = "Dr. Saumya Shukla"
DR_MADHURI_TRIPATHI = "Dr. Madhuri Tripathi"
DR_KRITIKA_PRASAD = "Dr. Kritika Prasad"
DR_ASHOK_KUMAR = "Dr. Ashok Kumar"
DR_HITESH_KUREEL = "Dr. Hitesh Kureel"

DR_SUNITA_OJHA = "Dr. Sunita Ojha"
DR_DEEPARK_SINGH = "Dr. Deepak Singh"
DR_RAJAT_GUPTA = "Dr. Rajat Gupta"
DR_VIKAS_VERMA = "Dr. Vikas Verma"
DR_ASHISH_GUPTA = "Dr. Ashish Gupta"
